apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/component: istio-operator.kyma-project.io
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: install-cni
              value: europe-docker.pkg.dev/kyma-project/prod/external/istio/install-cni:1.28.2-distroless
            - name: proxyv2
              value: europe-docker.pkg.dev/kyma-project/prod/external/istio/proxyv2:1.28.2-distroless
            - name: pilot
              value: europe-docker.pkg.dev/kyma-project/prod/external/istio/pilot:1.28.2-distroless
            - name: ztunnel
              value: europe-docker.pkg.dev/kyma-project/prod/external/istio/ztunnel:1.28.2-distroless
            - name: install-cni-fips
              value: europe-docker.pkg.dev/kyma-project/restricted-prod/sap.com/istio-install-cni-fips:1.28.2
            - name: proxyv2-fips
              value: europe-docker.pkg.dev/kyma-project/restricted-prod/sap.com/istio-proxy-fips:1.28.2
            - name: pilot-fips
              value: europe-docker.pkg.dev/kyma-project/restricted-prod/sap.com/istio-pilot-fips:1.28.2
            - name: ztunnel-fips
              value: europe-docker.pkg.dev/kyma-project/restricted-prod/sap.com/ztunnel-fips:1.28.2