resources:
  - GroupVersionKind:
      group: security.istio.io
      version: v1beta1
      kind: AuthorizationPolicy
  - GroupVersionKind:
      group: networking.istio.io
      version: v1alpha3
      kind: DestinationRule
  - GroupVersionKind:
      group: networking.istio.io
      version: v1alpha3
      kind: EnvoyFilter
    ControlledList:
      - name: "stats-filter-\\d\\.\\d\\d"
        namespace: "istio-system"
      - name: "tcp-stats-filter-\\d\\.\\d\\d"
        namespace: "istio-system"
  - GroupVersionKind:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
  - GroupVersionKind:
      group: install.istio.io
      version: v1alpha1
      kind: IstioOperator
    ControlledList:
      - name: "installed-state-default-operator"
        namespace: "istio-system"
  - GroupVersionKind:
      group: security.istio.io
      version: v1beta1
      kind: PeerAuthentication
  - GroupVersionKind:
      group: networking.istio.io
      version: v1beta1
      kind: ProxyConfig
  - GroupVersionKind:
      group: security.istio.io
      version: v1beta1
      kind: RequestAuthentication
  - GroupVersionKind:
      group: networking.istio.io
      version: v1alpha3
      kind: ServiceEntry
  - GroupVersionKind:
      group: networking.istio.io
      version: v1alpha3
      kind: Sidecar
  - GroupVersionKind:
      group: telemetry.istio.io
      version: v1alpha1
      kind: Telemetry
  - GroupVersionKind:
      group: networking.istio.io
      version: v1alpha3
      kind: VirtualService
  - GroupVersionKind:
      group: extensions.istio.io
      version: v1alpha1
      kind: WasmPlugin
  - GroupVersionKind:
      group: networking.istio.io
      version: v1alpha3
      kind: WorkloadEntry
  - GroupVersionKind:
      group: networking.istio.io
      version: v1alpha3
      kind: WorkloadGroup
