# permissions for end users to view istio.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: istio-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: istio
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/managed-by: kustomize
  name: istio-viewer-role
rules:
- apiGroups:
    - operator.kyma-project.io
  resources:
    - istios
  verbs:
    - get
    - list
    - watch
