configMapGenerator:
- name: authorizationpolicies-ui.operator.kyma-project.io
  namespace: kyma-system
  files:
  - general
  - form
  - list
  - details
  - translations
  - dataSources
  options:
    disableNameSuffixHash: true
    labels:
      busola.io/extension: resource
      busola.io/extension-version: "0.5"