name: Release Pull Request pipeline
on:
  pull_request_target:
    types: [ synchronize, opened, reopened, ready_for_review ]
    branches:
      - 'release-**'
jobs:
  build-image:
    name: Build manager image
    if: github.event.pull_request.draft == false
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: istio/pr/istio-manager
      dockerfile: Dockerfile
      context: .
      build-args: |
        VERSION=PR-${{ github.event.number }}

  unit-tests:
    name: Dispatch unit test
    uses: ./.github/workflows/call-unit-lint.yaml
    if: github.event.pull_request.draft == false
    secrets: inherit

  integration-tests:
    name: Dispatch integration tests
    needs: [build-image]
    uses: ./.github/workflows/pull-integration-release.yaml
    if: github.event.pull_request.draft == false
    secrets: inherit

  integration-tests-gardener:
    name: Dispatch Gardener integration tests
    needs: [build-image]
    uses: ./.github/workflows/pull-integration-gardener-release.yaml
    if: github.event.pull_request.draft == false
    secrets: inherit

  ui-tests:
    name: Dispatch UI tests
    needs: [build-image]
    uses: ./.github/workflows/ui-tests.yaml
    if: github.event.pull_request.draft == false
    secrets: inherit

  verify-pins:
    name: Dispatch verify-commit-pins
    uses: ./.github/workflows/verify-commit-pins.yaml
    if: github.event.pull_request.draft == false
    secrets: inherit

  pull-request-status:
    needs: [ build-image, unit-tests, integration-tests, integration-tests-gardener, ui-tests, verify-pins ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1